<a href="https://colab.research.google.com/github/Nahgalvao/Basic_Python/blob/main/Numpy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpay

https://numpy.org/doc/1.23/numpy-ref.pdf

https://numpy.org/doc/

https://numpy.org/devdocs/user/absolute_beginners.html

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [ ]:
import numpy as np

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


#Matrices

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a[0]) # Print the first line

[1 2 3 4]


In [ ]:
print(a[0,0]) # Prints a the first number of the first line

1


In [ ]:
print(a[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])

In [ ]:
z = np.zeros(3)
print(z)

[0. 0. 0.]


In [ ]:
o = np.ones(10)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
e = np.empty(3)
print(e)

[0. 0. 0.]


In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a = np.sort(arr) # Sort the values of 'arr' in order
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
for i in a:
  print(i)

1
2
3
4
5
6
7
8


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array ([5, 6, 7, 8])

print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]
